In [4]:
import pandas as pd 
from sqlalchemy import create_engine

In [5]:
engine = create_engine('sqlite:///../../dataset/us/us_ticker_with_indicator.db')
df = pd.read_sql('2022-08-26',con=engine)

In [6]:
df.rename(columns={'52week_low':'one_year_low',
                '52week_high':'one_year_high'},inplace=True)
df

,Open,High,Low,Close,Volume,datetime,MA10,MA20,MA50,MA150,MA200,VMA20,VMA50,symbol,one_year_high,one_year_low,rs
0,136.000000,136.050003,129.779999,129.869995,1252700.0,2022-08-26,135.267998,133.940499,125.944442,128.065623,134.166661,1373865.0,1490552.0,A,178.513828,112.321050,0.098
1,57.669998,58.235001,55.200001,55.840000,5504100.0,2022-08-26,53.220000,51.610017,48.263918,63.887112,61.245297,4753110.0,5731864.0,AA,97.724089,39.485100,0.356
2,9.890000,9.910000,9.890000,9.910000,104700.0,2022-08-26,9.884500,9.882250,9.858800,9.811433,9.804040,323135.0,372188.0,AAC,9.910000,9.660000,0.022
3,2.520000,2.570000,2.430000,2.470000,33400.0,2022-08-26,2.178000,1.698000,1.410600,2.136800,2.288450,59140.0,39046.0,AACG,7.500000,0.970000,1.253
4,9.900000,9.900000,9.900000,9.900000,1700.0,2022-08-26,9.919000,9.918500,9.895160,9.863260,9.846050,4790.0,19780.0,AACI,9.990000,9.340000,0.015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6116,30.559999,30.740000,28.750000,28.790001,521700.0,2022-08-26,30.429126,29.766796,29.031148,30.919458,32.082820,877630.0,1116930.0,ZWS,65.351546,25.842697,0.043
6117,2.570000,2.620000,2.410000,2.460000,381400.0,2022-08-26,2.715000,2.744000,2.151000,2.548433,3.811650,1279570.0,1719640.0,ZY,14.680000,1.100000,0.757
6118,7.180000,7.190000,6.585000,6.600000,355300.0,2022-08-26,6.687000,6.665000,6.217600,6.534600,9.134700,719190.0,853810.0,ZYME,37.189999,4.560000,0.175
6119,1.200000,1.250000,1.150000,1.230000,482900.0,2022-08-26,1.256000,1.236000,1.190000,1.582160,1.994370,535290.0,449578.0,ZYNE,4.650000,0.836000,0.299
6120,9.410000,9.410000,9.150000,9.240000,104800.0,2022-08-26,9.333000,9.260500,8.393800,7.298467,8.040985,223475.0,312136.0,ZYXI,14.080233,4.970000,0.605

In [ ]:
# # selection string
# conditon1 = 'Close > MA20'
# condi

In [19]:
df = df.query('Close > MA20 and Close > one_year_low*1.25 and Close> 12 and MA20 > MA50 > MA200')
df.index = range(len(df))
df['rs_rank'] = 0
for i in range(len(df)):
    val = df.iloc[i].rs
    df['rs_rank'].iloc[i] = int(round(df[df.rs < val].rs.count()  / len(df),2)*100)
res = df.sort_values(by='rs_rank', ascending=False)
ticker_list = res[res.rs_rank > 75].symbol.to_list()

In [8]:
df_con2 = df.query('Close > MA50 and Close > one_year_low*1.25  and Close > one_year_high*0.75 and Close> 12 and MA20 > MA50 > MA150 > MA200')
df_con2

,Open,High,Low,Close,Volume,datetime,MA10,MA20,MA50,MA150,MA200,VMA20,VMA50,symbol,one_year_high,one_year_low,rs
60,85.370003,86.029999,82.480003,82.639999,783400.0,2022-08-26,82.870999,82.084500,76.765800,68.615867,66.158550,501875.0,583848.0,ACHC,86.029999,50.070000,0.568
73,35.990002,36.000000,35.130001,35.380001,9200.0,2022-08-26,35.863000,35.332000,33.143200,33.062954,32.274515,18325.0,48364.0,ACNB,36.730000,26.481257,0.306
80,18.250000,18.250000,16.180000,16.459999,339000.0,2022-08-26,16.816000,16.565000,15.829200,14.607200,14.274800,368290.0,364250.0,ACRS,19.969999,9.260000,0.517
83,26.549999,26.559999,25.990000,26.160000,94900.0,2022-08-26,26.478625,25.990076,23.377848,22.567192,22.154649,179345.0,294050.0,ACT,27.531583,18.011928,0.327
92,78.139999,78.230003,76.970001,77.050003,431700.0,2022-08-26,78.849001,78.236501,75.512130,68.990540,68.511157,518055.0,668750.0,ADC,80.440002,60.404477,0.238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6003,69.199997,69.809998,67.620003,67.620003,272500.0,2022-08-26,70.349000,70.948500,66.836000,61.689563,58.844995,492340.0,718350.0,WWE,75.230003,46.722569,0.400
6014,76.250000,76.349998,74.910004,74.930000,2413300.0,2022-08-26,76.253001,75.312000,71.580600,70.984302,69.627163,2106480.0,2807324.0,XEL,77.529999,59.891003,0.210
6017,37.830002,38.220001,36.580002,36.970001,242300.0,2022-08-26,37.730000,37.199000,34.228000,31.393867,30.794500,521215.0,549888.0,XENE,41.389999,14.654000,1.229
6030,98.769997,99.910004,97.419998,97.870003,15516900.0,2022-08-26,95.199000,92.919598,89.316351,85.737319,79.853753,18301930.0,22924614.0,XOM,104.554122,50.668364,0.874
6053,841.780029,841.799988,841.080017,841.210022,34800.0,2022-08-26,841.170001,839.292999,836.164200,792.795733,762.477551,47595.0,83626.0,Y,862.869995,585.099976,0.337

In [9]:
ticker_list_con2 = df_con2.symbol.to_list()
ticker_list_con2

['ACHC',
 'ACNB',
 'ACRS',
 'ACT',
 'ADC',
 'AEP',
 'AJG',
 'AMAL',
 'AMR',
 'AORT',
 'APLS',
 'AR',
 'ARCH',
 'ARGX',
 'ARKR',
 'ARLP',
 'ARQT',
 'ARTNA',
 'ASAI',
 'ATGE',
 'ATI',
 'ATNI',
 'ATO',
 'AVAV',
 'AVT',
 'AXNX',
 'AXSM',
 'AZN',
 'AZPN',
 'BAH',
 'BANF',
 'BBSI',
 'BCBP',
 'BCOR',
 'BELFA',
 'BEPC',
 'BHVN',
 'BKH',
 'BRT',
 'BSM',
 'BTU',
 'CAH',
 'CALM',
 'CAPL',
 'CASY',
 'CBT',
 'CBZ',
 'CCBG',
 'CDR',
 'CEIX',
 'CF',
 'CHK',
 'CHNG',
 'CHRW',
 'CI',
 'CIX',
 'CLFD',
 'CLR',
 'CMT',
 'CMTG',
 'CNC',
 'CNP',
 'CORT',
 'CPB',
 'CPRX',
 'CRK',
 'CRT',
 'CSL',
 'CTO',
 'CTRA',
 'CTS',
 'CTVA',
 'CVBF',
 'CVEO',
 'CVET',
 'CVI',
 'CWCO',
 'CYTK',
 'DINO',
 'DK',
 'DKL',
 'DMLP',
 'DNOW',
 'DOX',
 'DTE',
 'DY',
 'EBF',
 'ED',
 'EPD',
 'EQNR',
 'EQT',
 'ERF',
 'ESQ',
 'ET',
 'ETR',
 'EURN',
 'EVH',
 'EVOP',
 'EXLS',
 'FAZE',
 'FCFS',
 'FDUS',
 'FHN',
 'FICO',
 'FLNG',
 'FPI',
 'FWONA',
 'GBT',
 'GCBC',
 'GCP',
 'GEF',
 'GIS',
 'GLNG',
 'GPC',
 'GPK',
 'GPOR',
 'GTLS',
 'HAE',
 'HEI',
 'HES',
 'HFWA',
 'HHS',
 'HII',
 'HOLI',
 'HP',
 'HRB',
 'HSY',
 'HUM',
 'HURN',
 'HWM',
 'HXL',
 'IBA',
 'IEA',
 'IMCR',
 'IMXI',
 'INSW',
 'IONS',
 'IRTC',
 'JAKK',
 'JAZZ',
 'JKHY',
 'JMSB',
 'K',
 'KBR',
 'KDNY',
 'KEQU',
 'KNSL',
 'KNTK',
 'KOF',
 'KRTX',
 'LGL',
 'LHCG',
 'LNG',
 'LNTH',
 'LPG',
 'LPLA',
 'LTC',
 'LW',
 'MANT',
 'MAYS',
 'MCK',
 'MERC',
 'MGPI',
 'MIRM',
 'MMP',
 'MN',
 'MNDT',
 'MNRL',
 'MNTK',
 'MPC',
 'MRTN',
 'MSB',
 'MTDR',
 'MUSA',
 'NBIX',
 'NBN',
 'NC',
 'NECB',
 'NEN',
 'NFE',
 'NFG',
 'NHI',
 'NJR',
 'NLSN',
 'NOC',
 'NOG',
 'NXST',
 'OFG',
 'OGE',
 'OHI',
 'OPCH',
 'ORA',
 'OXY',
 'PAA',
 'PAC',
 'PAG',
 'PAM',
 'PARR',
 'PBF',
 'PBFX',
 'PBR',
 'PBT',
 'PCVX',
 'PFGC',
 'PFHD',
 'PGR',
 'PLAB',
 'PNRG',
 'PNW',
 'POLY',
 'POST',
 'PRCT',
 'PRVA',
 'PSN',
 'PTCT',
 'PWR',
 'RBCN',
 'RELL',
 'RFP',
 'RGA',
 'RGP',
 'RLMD',
 'RNDB',
 'RPRX',
 'RRC',
 'RTLR',
 'RXDX',
 'RYAN',
 'SAIL',
 'SANM',
 'SBOW',
 'SBR',
 'SBRA',
 'SCHL',
 'SGFY',
 'SGML',
 'SHLX',
 'SIRE',
 'SJT',
 'SLP',
 'SMCI',
 'SMMF',
 'SNEX',
 'SO',
 'SON',
 'SP',
 'SPH',
 'SPLP',
 'SPTN',
 'SQM',
 'SRE',
 'SRLP',
 'SRTS',
 'SSBK',
 'STNG',
 'STR',
 'SWAV',
 'SWCH',
 'SWIR',
 'TALO',
 'TCBK',
 'TCDA',
 'TCI',
 'TDW',
 'TEN',
 'TH',
 'THFF',
 'TMDX',
 'TMUS',
 'TNK',
 'TNP',
 'TPL',
 'TPTX',
 'TR',
 'TRMD',
 'TWNK',
 'TYG',
 'UFPT',
 'ULH',
 'UNH',
 'UNM',
 'USAC',
 'USAK',
 'VALU',
 'VET',
 'VICI',
 'VIVO',
 'VLO',
 'VRRM',
 'VST',
 'VTRU',
 'WDS',
 'WES',
 'WMK',
 'WTM',
 'WWE',
 'XEL',
 'XENE',
 'XOM',
 'Y']

In [12]:
ticker_df = df_con2[['symbol']]
ticker_df.index = range(len(df_con2))
ticker_df.to_csv('selected_ticker_list_08_28.csv',index=None)