# Get ticker symbol

## SSE SH

In [6]:
# Pandas
import pandas as pd
import talib as ta
import numpy as np
# from get_score import get_score_ch
from sqlalchemy import create_engine
engine= create_engine('sqlite:///ticker_symbol_ch.db')

In [7]:
df = pd.read_sql('SSE',engine)

In [8]:
df

        ts_code  symbol     name industry exchange
0     600000.SH  600000     浦发银行       银行      SSE
1     600004.SH  600004     白云机场       机场      SSE
2     600006.SH  600006     东风汽车     汽车整车      SSE
3     600007.SH  600007     中国国贸     园区开发      SSE
4     600008.SH  600008     首创环保     环境保护      SSE
...         ...     ...      ...      ...      ...
2087  688799.SH  688799     华纳药厂     化学制药      SSE
2088  688800.SH  688800      瑞可达      元器件      SSE
2089  688819.SH  688819     天能股份     电气设备      SSE
2090  688981.SH  688981     中芯国际      半导体      SSE
2091  689009.SH  689009  九号公司-WD      摩托车      SSE

[2092 rows x 5 columns]

# Change the symbol code

In [11]:
df.symbol = 'sh.' + df.symbol.astype(str)

In [13]:
df.head()

     ts_code     symbol  name industry exchange
0  600000.SH  sh.600000  浦发银行       银行      SSE
1  600004.SH  sh.600004  白云机场       机场      SSE
2  600006.SH  sh.600006  东风汽车     汽车整车      SSE
3  600007.SH  sh.600007  中国国贸     园区开发      SSE
4  600008.SH  sh.600008  首创环保     环境保护      SSE

# Get Single Ticker Price

## Connect to database

In [16]:
# 存入数据库
## Write into SQL
import sqlite3
#
import pandas as pd 
from datetime import datetime
## connect database
database = "./single_ticker_price/ch/ch_ticker_price.db"
conn = sqlite3.connect(database)
print('connect success!')

connect success!

In [17]:
import baostock as bs
import pandas as pd

#### 登陆系统 ####
lg = bs.login()

for ticker in ticker_list:
    #### 获取沪深A股历史K线数据 ####
    # 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
    # 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
    # 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
    rs = bs.query_history_k_data_plus("{}".format(ticker),
        "date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST",
        frequency="d", adjustflag="3")

    #### 打印结果集 ####
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())
    result = pd.DataFrame(data_list, columns=rs.fields)

    #### 结果集输出到csv文件 ####   
    # result.to_csv("D:\\history_A_stock_k_data.csv", index=False)


    #### 结果输出到SQL ####
    try:
        cursor = conn.cursor()
        cursor.execute('CREATE TABLE {}(date, code, open, high, low, close, volume, amount, pctChg)'.format(ticker))
        conn.commit()
        print("Table ceate successful!")
    except:
        print("Table name already exists")
    
    # 写入（如果没有就写入，否则建立资料表）
    try:
        result.to_sql('{}'.format(ticker), conn, if_exists='replace',index=False)
    except:
        print('df already exits')

#### 登出系统 ####
bs.logout()

login success!
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists

In [2]:
# Pandas
import pandas as pd
import talib as ta
import numpy as np
# from get_score import get_score_ch
from sqlalchemy import create_engine
engine= create_engine('sqlite:///ticker_symbol_ch.db')

In [3]:
df = pd.read_sql('SZSE',engine)
df

        ts_code  symbol  name industry exchange
0     000001.SZ  000001  平安银行       银行     SZSE
1     000002.SZ  000002   万科A     全国地产     SZSE
2     000004.SZ  000004  ST国华     软件服务     SZSE
3     000005.SZ  000005  ST星源     环境保护     SZSE
4     000006.SZ  000006  深振业A     区域地产     SZSE
...         ...     ...   ...      ...      ...
2630  301288.SZ  301288  清研环境     环境保护     SZSE
2631  301289.SZ  301289  国缆检测      综合类     SZSE
2632  301298.SZ  301298  东利机械     汽车配件     SZSE
2633  301302.SZ  301302  华如科技     软件服务     SZSE
2634  301312.SZ  301312  C智立方     专用机械     SZSE

[2635 rows x 5 columns]

In [4]:
df = pd.read_sql('SZSE',engine)
df.symbol = 'sz.' + df.symbol.astype(str)
ticker_list = df.symbol.to_list()

In [5]:
len(ticker_list)

2635

In [24]:
# 存入数据库
## Write into SQL
import sqlite3
#
import pandas as pd 
from datetime import datetime
## connect database
database = "./single_ticker_price/ch/ch_ticker_price.db"
conn = sqlite3.connect(database)
print('connect success!')

connect success!

In [25]:
import baostock as bs
import pandas as pd

#### 登陆系统 ####
lg = bs.login()

for ticker in ticker_list:
    #### 获取沪深A股历史K线数据 ####
    # 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
    # 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
    # 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
    rs = bs.query_history_k_data_plus("{}".format(ticker),
        "date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST",
        frequency="d", adjustflag="3")

    #### 打印结果集 ####
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())
    result = pd.DataFrame(data_list, columns=rs.fields)

    #### 结果集输出到csv文件 ####   
    # result.to_csv("D:\\history_A_stock_k_data.csv", index=False)


    #### 结果输出到SQL ####
    try:
        cursor = conn.cursor()
        cursor.execute('CREATE TABLE {}(date, code, open, high, low, close, volume, amount, pctChg)'.format(ticker))
        conn.commit()
        print("Table ceate successful!")
    except:
        print("Table name already exists")
    
    # 写入（如果没有就写入，否则建立资料表）
    try:
        result.to_sql('{}'.format(ticker), conn, if_exists='replace',index=False)
    except:
        print('df already exits')

#### 登出系统 ####
bs.logout()

login success!
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists