In [1]:
import sqlite3
import pandas as pd
import tushare as ts

In [6]:
# Select SSE List
conn = sqlite3.connect('ticker_symbol_ch.db')
cur = conn.cursor()
sql = """select * from SSE"""
cur.execute(sql)
rows = cur.fetchall()
cur.close()
conn.close()
pro = ts.pro_api()

In [7]:
rows

[('600000.SH', 600000, '浦发银行', '银行', 'SSE'),
 ('600004.SH', 600004, '白云机场', '机场', 'SSE'),
 ('600006.SH', 600006, '东风汽车', '汽车整车', 'SSE'),
 ('600007.SH', 600007, '中国国贸', '园区开发', 'SSE'),
 ('600008.SH', 600008, '首创环保', '环境保护', 'SSE'),
 ('600009.SH', 600009, '上海机场', '机场', 'SSE'),
 ('600010.SH', 600010, '包钢股份', '普钢', 'SSE'),
 ('600011.SH', 600011, '华能国际', '火力发电', 'SSE'),
 ('600012.SH', 600012, '皖通高速', '路桥', 'SSE'),
 ('600015.SH', 600015, '华夏银行', '银行', 'SSE'),
 ('600016.SH', 600016, '民生银行', '银行', 'SSE'),
 ('600017.SH', 600017, '日照港', '港口', 'SSE'),
 ('600018.SH', 600018, '上港集团', '港口', 'SSE'),
 ('600019.SH', 600019, '宝钢股份', '普钢', 'SSE'),
 ('600020.SH', 600020, '中原高速', '路桥', 'SSE'),
 ('600021.SH', 600021, '上海电力', '火力发电', 'SSE'),
 ('600022.SH', 600022, '山东钢铁', '普钢', 'SSE'),
 ('600023.SH', 600023, '浙能电力', '火力发电', 'SSE'),
 ('600025.SH', 600025, '华能水电', '水力发电', 'SSE'),
 ('600026.SH', 600026, '中远海能', '水运', 'SSE'),
 ('600027.SH', 600027, '华电国际', '火力发电', 'SSE'),
 ('600028.SH', 600028, '中国石化', '石油加工', 'SSE'),
 ('600029.SH', 600029, '南方航空', '空运', 'SSE'),
 ('600030.SH', 600030, '中信证券', '证券', 'SSE'),
 ('600031.SH', 600031, '三一重工', '工程机械', 'SSE'),
 ('600032.SH', 600032, '浙江新能', '新型电力', 'SSE'),
 ('600033.SH', 600033, '福建高速', '路桥', 'SSE'),
 ('600035.SH', 600035, '楚天高速', '路桥', 'SSE'),
 ('600036.SH', 600036, '招商银行', '银行', 'SSE'),
 ('600037.SH', 600037, '歌华有线', '影视音像', 'SSE'),
 ('600038.SH', 600038, '中直股份', '航空', 'SSE'),
 ('600039.SH', 600039, '四川路桥', '建筑工程', 'SSE'),
 ('600048.SH', 600048, '保利发展', '全国地产', 'SSE'),
 ('600050.SH', 600050, '中国联通', '电信运营', 'SSE'),
 ('600051.SH', 600051, '宁波联合', '综合类', 'SSE'),
 ('600052.SH', 600052, '东望时代', '影视音像', 'SSE'),
 ('600053.SH', 600053, '九鼎投资', '多元金融', 'SSE'),
 ('600054.SH', 600054, '黄山旅游', '旅游景点', 'SSE'),
 ('600055.SH', 600055, '万东医疗', '医疗保健', 'SSE'),
 ('600056.SH', 600056, '中国医药', '医药商业', 'SSE'),
 ('600057.SH', 600057, '厦门象屿', '仓储物流', 'SSE'),
 ('600058.SH', 600058, '五矿发展', '商贸代理', 'SSE'),
 ('600059.SH', 600059, '古越龙山', '红黄酒', 'SSE'),
 ('600060.SH', 600060, '海信视像', '家用电器', 'SSE'),
 ('600061.SH', 600061, '国投资本', '证券', 'SSE'),
 ('600062.SH', 600062, '华润双鹤', '化学制药', 'SSE'),
 ('600063.SH', 600063, '皖维高新', '化纤', 'SSE'),
 ('600064.SH', 600064, '南京高科', '园区开发', 'SSE'),
 ('600066.SH', 600066, '宇通客车', '汽车整车', 'SSE'),
 ('600067.SH', 600067, '冠城大通', '电气设备', 'SSE'),
 ('600070.SH', 600070, '浙江富润', '互联网', 'SSE'),
 ('600071.SH', 600071, '凤凰光学', '元器件', 'SSE'),
 ('600072.SH', 600072, '中船科技', '船舶', 'SSE'),
 ('600073.SH', 600073, '上海梅林', '食品', 'SSE'),
 ('600075.SH', 600075, '新疆天业', '化工原料', 'SSE'),
 ('600076.SH', 600076, '康欣新材', '其他建材', 'SSE'),
 ('600077.SH', 600077, '宋都股份', '全国地产', 'SSE'),
 ('600078.SH', 600078, '*ST澄星', '化工原料', 'SSE'),
 ('600079.SH', 600079, '人福医药', '化学制药', 'SSE'),
 ('600080.SH', 600080, '金花股份', '中成药', 'SSE'),
 ('600081.SH', 600081, '东风科技', '汽车配件', 'SSE'),
 ('600082.SH', 600082, '海泰发展', '园区开发', 'SSE'),
 ('600083.SH', 600083, '*ST博信', '综合类', 'SSE'),
 ('600084.SH', 600084, '中葡股份', '红黄酒', 'SSE'),
 ('600085.SH', 600085, '同仁堂', '中成药', 'SSE'),
 ('600088.SH', 600088, '中视传媒', '影视音像', 'SSE'),
 ('600089.SH', 600089, '特变电工', '电气设备', 'SSE'),
 ('600094.SH', 600094, '大名城', '区域地产', 'SSE'),
 ('600095.SH', 600095, '湘财股份', '证券', 'SSE'),
 ('600096.SH', 600096, '云天化', '农药化肥', 'SSE'),
 ('600097.SH', 600097, '开创国际', '渔业', 'SSE'),
 ('600098.SH', 600098, '广州发展', '火力发电', 'SSE'),
 ('600099.SH', 600099, '林海股份', '汽车整车', 'SSE'),
 ('600100.SH', 600100, '同方股份', 'IT设备', 'SSE'),
 ('600101.SH', 600101, '明星电力', '水力发电', 'SSE'),
 ('600103.SH', 600103, '青山纸业', '造纸', 'SSE'),
 ('600104.SH', 600104, '上汽集团', '汽车整车', 'SSE'),
 ('600105.SH', 600105, '永鼎股份', '通信设备', 'SSE'),
 ('600106.SH', 600106, '重庆路桥', '路桥', 'SSE'),
 ('600107.SH', 600107, '美尔雅', '服饰', 'SSE'),
 ('600108.SH', 600108, '亚盛集团', '种植业', 'SSE'),
 ('600109.SH', 600109, '国金证券', '证券', 'SSE'),
 ('600110.SH', 600110, '诺德股份', '铜', 'SSE'),
 ('600111.SH', 600111, '北方稀土', '小金属', 'SSE'),
 ('600112.SH', 600112, '*ST天成', '电气设备', 'SSE'),
 ('600113.SH', 600113, '浙江东日', '区域地产', 'SSE'),
 ('600114.SH', 600114, '东睦股份', '机械基件', 'SSE'),
 ('600115.SH', 600115, '中国东航', '空运', 'SSE'),
 ('600116.SH', 600116, '三峡水利', '水力发电', 'SSE'),
 ('600117.SH', 600117, '西宁特钢', '特种钢', 'SSE'),
 ('600118.SH', 600118, '中国卫星', '航空', 'SSE'),
 ('600119.SH', 600119, '长江投资', '仓储物流', 'SSE'),
 ('600120.SH', 600120, '浙江东方', '多元金融', 'SSE'),
 ('600121.SH', 600121, '郑州煤电', '煤炭开采', 'SSE'),
 ('600122.SH', 600122, 'ST宏图', '其他商业', 'SSE'),
 ('600123.SH', 600123, '兰花科创', '煤炭开采', 'SSE'),
 ('600125.SH', 600125, '铁龙物流', '铁路', 'SSE'),
 ('600126.SH', 600126, '杭钢股份', '普钢', 'SSE'),
 ('600127.SH', 600127, '金健米业', '农业综合', 'SSE'),
 ('600128.SH', 600128, '弘业股份', '商贸代理', 'SSE'),
 ('600129.SH', 600129, '太极集团', '中成药', 'SSE'),
 ('600130.SH', 600130, '波导股份', '通信设备', 'SSE'),
 ('600131.SH', 600131, '国网信通', '通信设备', 'SSE'),
 ('600132.SH', 600132, '重庆啤酒', '啤酒', 'SSE'),
 ('600133.SH', 600133, '东湖高新', '园区开发', 'SSE'),
 ('600135.SH', 600135, '乐凯胶片', '化工原料', 'SSE'),
 ('600136.SH', 600136, 'ST明诚', '影视音像', 'SSE'),
 ('600137.SH', 600137, '浪莎股份', '服饰', 'SSE'),
 ('600138.SH', 600138, '中青旅', '旅游服务', 'SSE'),
 ('600139.SH', 600139, '*ST西源', '综合类', 'SSE'),
 ('600141.SH', 600141, '兴发集团', '农药化肥', 'SSE'),
 ('600143.SH', 600143, '金发科技', '塑料', 'SSE'),
 ('600148.SH', 600148, '长春一东', '汽车配件', 'SSE'),
 ('600149.SH', 600149, '廊坊发展', '综合类', 'SSE'),
 ('600150.SH', 600150, '中国船舶', '船舶', 'SSE'),
 ('600151.SH', 600151, '航天机电', '汽车配件', 'SSE'),
 ('600152.SH', 600152, '维科技术', '电气设备', 'SSE'),
 ('600153.SH', 600153, '建发股份', '仓储物流', 'SSE'),
 ('600155.SH', 600155, '华创阳安', '证券', 'SSE'),
 ('600156.SH', 600156, '华升股份', '纺织', 'SSE'),
 ('600157.SH', 600157, '永泰能源', '火力发电', 'SSE'),
 ('600158.SH', 600158, '中体产业', '文教休闲', 'SSE'),
 ('600159.SH', 600159, '大龙地产', '区域地产', 'SSE'),
 ('600160.SH', 600160, '巨化股份', '化工原料', 'SSE'),
 ('600161.SH', 600161, '天坛生物', '生物制药', 'SSE'),
 ('600162.SH', 600162, '香江控股', '全国地产', 'SSE'),
 ('600163.SH', 600163, '中闽能源', '新型电力', 'SSE'),
 ('600165.SH', 600165, '新日恒力', '化工原料', 'SSE'),
 ('600166.SH', 600166, '福田汽车', '汽车整车', 'SSE'),
 ('600167.SH', 600167, '联美控股', '供气供热', 'SSE'),
 ('600168.SH', 600168, '武汉控股', '水务', 'SSE'),
 ('600169.SH', 600169, '太原重工', '工程机械', 'SSE'),
 ('600170.SH', 600170, '上海建工', '建筑工程', 'SSE'),
 ('600171.SH', 600171, '上海贝岭', '半导体', 'SSE'),
 ('600172.SH', 600172, '黄河旋风', '矿物制品', 'SSE'),
 ('600173.SH', 600173, '卧龙地产', '全国地产', 'SSE'),
 ('600176.SH', 600176, '中国巨石', '玻璃', 'SSE'),
 ('600177.SH', 600177, '雅戈尔', '服饰', 'SSE'),
 ('600178.SH', 600178, '东安动力', '汽车配件', 'SSE'),
 ('600179.SH', 600179, '安通控股', '仓储物流', 'SSE'),
 ('600180.SH', 600180, '瑞茂通', '仓储物流', 'SSE'),
 ('600182.SH', 600182, 'S*ST佳通', '汽车配件', 'SSE'),
 ('600183.SH', 600183, '生益科技', '元器件', 'SSE'),
 ('600184.SH', 600184, '光电股份', '专用机械', 'SSE'),
 ('600185.SH', 600185, '格力地产', '区域地产', 'SSE'),
 ('600186.SH', 600186, '莲花健康', '食品', 'SSE'),
 ('600187.SH', 600187, '国中水务', '水务', 'SSE'),
 ('600188.SH', 600188, '兖矿能源', '煤炭开采', 'SSE'),
 ('600189.SH', 600189, '泉阳泉', '软饮料', 'SSE'),
 ('600190.SH', 600190, '锦州港', '港口', 'SSE'),
 ('600191.SH', 600191, '*ST华资', '食品', 'SSE'),
 ('600192.SH', 600192, '长城电工', '电气设备', 'SSE'),
 ('600193.SH', 600193, '创兴资源', '装修装饰', 'SSE'),
 ('600195.SH', 600195, '中牧股份', '农业综合', 'SSE'),
 ('600196.SH', 600196, '复星医药', '化学制药', 'SSE'),
 ('600197.SH', 600197, '伊力特', '白酒', 'SSE'),
 ('600198.SH', 600198, '大唐电信', '通信设备', 'SSE'),
 ('600199.SH', 600199, '金种子酒', '白酒', 'SSE'),
 ('600200.SH', 600200, '江苏吴中', '化学制药', 'SSE'),
 ('600201.SH', 600201, '生物股份', '农业综合', 'SSE'),
 ('600202.SH', 600202, '哈空调', '专用机械', 'SSE'),
 ('600203.SH', 600203, '福日电子', '元器件', 'SSE'),
 ('600206.SH', 600206, '有研新材', '半导体', 'SSE'),
 ('600207.SH', 600207, '安彩高科', '供气供热', 'SSE'),
 ('600208.SH', 600208, '新湖中宝', '全国地产', 'SSE'),
 ('600210.SH', 600210, '紫江企业', '广告包装', 'SSE'),
 ('600211.SH', 600211, '西藏药业', '中成药', 'SSE'),
 ('600212.SH', 600212, '绿能慧充', '综合类', 'SSE'),
 ('600213.SH', 600213, '亚星客车', '汽车整车', 'SSE'),
 ('600215.SH', 600215, '派斯林', '专用机械', 'SSE'),
 ('600216.SH', 600216, '浙江医药', '化学制药', 'SSE'),
 ('600217.SH', 600217, '中再资环', '环境保护', 'SSE'),
 ('600218.SH', 600218, '全柴动力', '农用机械', 'SSE'),
 ('600219.SH', 600219, '南山铝业', '铝', 'SSE'),
 ('600220.SH', 600220, '江苏阳光', '纺织', 'SSE'),
 ('600221.SH', 600221, 'ST海航', '空运', 'SSE'),
 ('600222.SH', 600222, '太龙药业', '中成药', 'SSE'),
 ('600223.SH', 600223, '鲁商发展', '区域地产', 'SSE'),
 ('600225.SH', 600225, '天津松江', '区域地产', 'SSE'),
 ('600226.SH', 600226, 'ST瀚叶', '互联网', 'SSE'),
 ('600227.SH', 600227, '圣济堂', '农药化肥', 'SSE'),
 ('600228.SH', 600228, '返利科技', '互联网', 'SSE'),
 ('600229.SH', 600229, '城市传媒', '出版业', 'SSE'),
 ('600230.SH', 600230, '沧州大化', '化工原料', 'SSE'),
 ('600231.SH', 600231, '凌钢股份', '普钢', 'SSE'),
 ('600232.SH', 600232, '金鹰股份', '纺织', 'SSE'),
 ('600233.SH', 600233, '圆通速递', '仓储物流', 'SSE'),
 ('600234.SH', 600234, '科新发展', '综合类', 'SSE'),
 ('600235.SH', 600235, '民丰特纸', '造纸', 'SSE'),
 ('600236.SH', 600236, '桂冠电力', '水力发电', 'SSE'),
 ('600237.SH', 600237, '铜峰电子', '元器件', 'SSE'),
 ('600238.SH', 600238, '海南椰岛', '红黄酒', 'SSE'),
 ('600239.SH', 600239, 'ST云城', '区域地产', 'SSE'),
 ('600241.SH', 600241, 'ST时万', '电气设备', 'SSE'),
 ('600242.SH', 600242, '*ST中昌', '软件服务', 'SSE'),
 ('600243.SH', 600243, '青海华鼎', '机床制造', 'SSE'),
 ('600246.SH', 600246, '万通发展', '区域地产', 'SSE'),
 ('600248.SH', 600248, '陕西建工', '建筑工程', 'SSE'),
 ('600249.SH', 600249, '两面针', '日用化工', 'SSE'),
 ('600250.SH', 600250, '南纺股份', '商贸代理', 'SSE'),
 ('600251.SH', 600251, '冠农股份', '农业综合', 'SSE'),
 ('600252.SH', 600252, '中恒集团', '中成药', 'SSE'),
 ('600255.SH', 600255, '鑫科材料', '小金属', 'SSE'),
 ('600256.SH', 600256, '广汇能源', '石油开采', 'SSE'),
 ('600257.SH', 600257, '大湖股份', '渔业', 'SSE'),
 ('600258.SH', 600258, '首旅酒店', '酒店餐饮', 'SSE'),
 ('600259.SH', 600259, '广晟有色', '小金属', 'SSE'),
 ('600260.SH', 600260, '*ST凯乐', '通信设备', 'SSE'),
 ('600261.SH', 600261, '阳光照明', '家用电器', 'SSE'),
 ('600262.SH', 600262, '北方股份', '专用机械', 'SSE'),
 ('600265.SH', 600265, '*ST景谷', '林业', 'SSE'),
 ('600266.SH', 600266, '城建发展', '区域地产', 'SSE'),
 ('600267.SH', 600267, '海正药业', '化学制药', 'SSE'),
 ('600268.SH', 600268, '国电南自', '电气设备', 'SSE'),
 ('600269.SH', 600269, '赣粤高速', '路桥', 'SSE'),
 ('600271.SH', 600271, '航天信息', 'IT设备', 'SSE'),
 ('600272.SH', 600272, '开开实业', '医药商业', 'SSE'),
 ('600273.SH', 600273, '嘉化能源', '化工原料', 'SSE'),
 ('600276.SH', 600276, '恒瑞医药', '化学制药', 'SSE'),
 ('600277.SH', 600277, '亿利洁能', '化工原料', 'SSE'),
 ('600278.SH', 600278, '东方创业', '商贸代理', 'SSE'),
 ('600279.SH', 600279, '重庆港', '港口', 'SSE'),
 ('600280.SH', 600280, '中央商场', '百货', 'SSE'),
 ('600281.SH', 600281, '华阳新材', '小金属', 'SSE'),
 ('600282.SH', 600282, '南钢股份', '普钢', 'SSE'),
 ('600283.SH', 600283, '钱江水利', '水务', 'SSE'),
 ('600284.SH', 600284, '浦东建设', '建筑工程', 'SSE'),
 ('600285.SH', 600285, '羚锐制药', '中成药', 'SSE'),
 ('600287.SH', 600287, '江苏舜天', '商贸代理', 'SSE'),
 ('600288.SH', 600288, '大恒科技', '元器件', 'SSE'),
 ('600289.SH', 600289, 'ST信通', '软件服务', 'SSE'),
 ('600290.SH', 600290, 'ST华仪', '电气设备', 'SSE'),
 ('600292.SH', 600292, '远达环保', '环境保护', 'SSE'),
 ('600293.SH', 600293, '三峡新材', '玻璃', 'SSE'),
 ('600295.SH', 600295, '鄂尔多斯', '特种钢', 'SSE'),
 ('600297.SH', 600297, '广汇汽车', '汽车服务', 'SSE'),
 ('600298.SH', 600298, '安琪酵母', '食品', 'SSE'),
 ('600299.SH', 600299, '安迪苏', '化学制药', 'SSE'),
 ('600300.SH', 600300, '维维股份', '软饮料', 'SSE'),
 ('600301.SH', 600301, '南化股份', '商贸代理', 'SSE'),
 ('600302.SH', 600302, '标准股份', '纺织机械', 'SSE'),
 ('600303.SH', 600303, 'ST曙光', '汽车整车', 'SSE'),
 ('600305.SH', 600305, '恒顺醋业', '食品', 'SSE'),
 ('600306.SH', 600306, 'ST商城', '百货', 'SSE'),
 ('600307.SH', 600307, '酒钢宏兴', '普钢', 'SSE'),
 ('600308.SH', 600308, '华泰股份', '造纸', 'SSE'),
 ('600309.SH', 600309, '万华化学', '化工原料', 'SSE'),
 ('600310.SH', 600310, '桂东电力', '水力发电', 'SSE'),
 ('600311.SH', 600311, '*ST荣华', '黄金', 'SSE'),
 ('600312.SH', 600312, '平高电气', '电气设备', 'SSE'),
 ('600313.SH', 600313, '农发种业', '种植业', 'SSE'),
 ('600315.SH', 600315, '上海家化', '日用化工', 'SSE'),
 ('600316.SH', 600316, '洪都航空', '航空', 'SSE'),
 ('600318.SH', 600318, '新力金融', '多元金融', 'SSE'),
 ('600319.SH', 600319, '亚星化学', '化工原料', 'SSE'),
 ('600320.SH', 600320, '振华重工', '工程机械', 'SSE'),
 ('600321.SH', 600321, '正源股份', '其他建材', 'SSE'),
 ('600322.SH', 600322, '天房发展', '区域地产', 'SSE'),
 ('600323.SH', 600323, '瀚蓝环境', '环境保护', 'SSE'),
 ('600325.SH', 600325, '华发股份', '区域地产', 'SSE'),
 ('600326.SH', 600326, '西藏天路', '水泥', 'SSE'),
 ('600327.SH', 600327, '大东方', '医疗保健', 'SSE'),
 ('600328.SH', 600328, '中盐化工', '化工原料', 'SSE'),
 ('600329.SH', 600329, '达仁堂', '中成药', 'SSE'),
 ('600330.SH', 600330, '天通股份', '元器件', 'SSE'),
 ('600331.SH', 600331, '宏达股份', '铅锌', 'SSE'),
 ('600332.SH', 600332, '白云山', '中成药', 'SSE'),
 ('600333.SH', 600333, '长春燃气', '供气供热', 'SSE'),
 ('600335.SH', 600335, '国机汽车', '汽车配件', 'SSE'),
 ('600336.SH', 600336, '澳柯玛', '家用电器', 'SSE'),
 ('600337.SH', 600337, '美克家居', '家居用品', 'SSE'),
 ('600338.SH', 600338, '西藏珠峰', '铅锌', 'SSE'),
 ('600339.SH', 600339, '中油工程', '石油加工', 'SSE'),
 ('600340.SH', 600340, '华夏幸福', '区域地产', 'SSE'),
 ('600343.SH', 600343, '航天动力', '航空', 'SSE'),
 ('600345.SH', 600345, '长江通信', '通信设备', 'SSE'),
 ('600346.SH', 600346, '恒力石化', '石油加工', 'SSE'),
 ('600348.SH', 600348, '华阳股份', '煤炭开采', 'SSE'),
 ('600350.SH', 600350, '山东高速', '路桥', 'SSE'),
 ('600351.SH', 600351, '亚宝药业', '中成药', 'SSE'),
 ('600352.SH', 600352, '浙江龙盛', '染料涂料', 'SSE'),
 ('600353.SH', 600353, '旭光电子', '元器件', 'SSE'),
 ('600354.SH', 600354, '敦煌种业', '种植业', 'SSE'),
 ('600355.SH', 600355, '精伦电子', '元器件', 'SSE'),
 ('600356.SH', 600356, '恒丰纸业', '造纸', 'SSE'),
 ('600358.SH', 600358, '国旅联合', '旅游服务', 'SSE'),
 ('600359.SH', 600359, '新农开发', '农业综合', 'SSE'),
 ('600360.SH', 600360, '华微电子', '半导体', 'SSE'),
 ('600361.SH', 600361, '华联综超', '超市连锁', 'SSE'),
 ('600362.SH', 600362, '江西铜业', '铜', 'SSE'),
 ('600363.SH', 600363, '联创光电', '元器件', 'SSE'),
 ('600365.SH', 600365, 'ST通葡', '红黄酒', 'SSE'),
 ('600366.SH', 600366, '宁波韵升', '矿物制品', 'SSE'),
 ('600367.SH', 600367, '红星发展', '化工原料', 'SSE'),
 ('600368.SH', 600368, '五洲交通', '路桥', 'SSE'),
 ('600369.SH', 600369, '西南证券', '证券', 'SSE'),
 ('600370.SH', 600370, '三房巷', '化工原料', 'SSE'),
 ('600371.SH', 600371, '万向德农', '种植业', 'SSE'),
 ('600372.SH', 600372, '中航电子', '航空', 'SSE'),
 ('600373.SH', 600373, '中文传媒', '出版业', 'SSE'),
 ('600375.SH', 600375, '汉马科技', '汽车整车', 'SSE'),
 ('600376.SH', 600376, '首开股份', '区域地产', 'SSE'),
 ('600377.SH', 600377, '宁沪高速', '路桥', 'SSE'),
 ('600378.SH', 600378, '昊华科技', '化工原料', 'SSE'),
 ('600379.SH', 600379, '宝光股份', '电气设备', 'SSE'),
 ('600380.SH', 600380, '健康元', '化学制药', 'SSE'),
 ('600381.SH', 600381, '青海春天', '医疗保健', 'SSE'),
 ('600382.SH', 600382, 'ST广珠', '普钢', 'SSE'),
 ('600383.SH', 600383, '金地集团', '全国地产', 'SSE'),
 ('600386.SH', 600386, '北巴传媒', '汽车服务', 'SSE'),
 ('600387.SH', 600387, 'ST海越', '石油贸易', 'SSE'),
 ('600388.SH', 600388, 'ST龙净', '环境保护', 'SSE'),
 ('600389.SH', 600389, '江山股份', '农药化肥', 'SSE'),
 ('600390.SH', 600390, '五矿资本', '多元金融', 'SSE'),
 ('600391.SH', 600391, '航发科技', '航空', 'SSE'),
 ('600392.SH', 600392, '盛和资源', '小金属', 'SSE'),
 ('600393.SH', 600393, '粤泰股份', '全国地产', 'SSE'),
 ('600395.SH', 600395, '盘江股份', '煤炭开采', 'SSE'),
 ('600396.SH', 600396, '金山股份', '火力发电', 'SSE'),
 ('600397.SH', 600397, '安源煤业', '煤炭开采', 'SSE'),
 ('600398.SH', 600398, '海澜之家', '服饰', 'SSE'),
 ('600399.SH', 600399, '抚顺特钢', '特种钢', 'SSE'),
 ('600400.SH', 600400, '红豆股份', '服饰', 'SSE'),
 ('600403.SH', 600403, '大有能源', '煤炭开采', 'SSE'),
 ('600405.SH', 600405, '动力源', '电气设备', 'SSE'),
 ('600406.SH', 600406, '国电南瑞', '电气设备', 'SSE'),
 ('600408.SH', 600408, '安泰集团', '焦炭加工', 'SSE'),
 ('600409.SH', 600409, '三友化工', '化纤', 'SSE'),
 ('600410.SH', 600410, '华胜天成', '软件服务', 'SSE'),
 ('600415.SH', 600415, '小商品城', '商品城', 'SSE'),
 ('600416.SH', 600416, '湘电股份', '电气设备', 'SSE'),
 ('600418.SH', 600418, '江淮汽车', '汽车整车', 'SSE'),
 ('600419.SH', 600419, '天润乳业', '乳制品', 'SSE'),
 ('600420.SH', 600420, '国药现代', '化学制药', 'SSE'),
 ('600421.SH', 600421, '华嵘控股', '专用机械', 'SSE'),
 ('600422.SH', 600422, '昆药集团', '中成药', 'SSE'),
 ('600423.SH', 600423, '柳化股份', '农药化肥', 'SSE'),
 ('600425.SH', 600425, '青松建化', '水泥', 'SSE'),
 ('600426.SH', 600426, '华鲁恒升', '农药化肥', 'SSE'),
 ('600428.SH', 600428, '中远海特', '水运', 'SSE'),
 ('600429.SH', 600429, '三元股份', '乳制品', 'SSE'),
 ('600433.SH', 600433, '冠豪高新', '造纸', 'SSE'),
 ('600435.SH', 600435, '北方导航', '专用机械', 'SSE'),
 ('600436.SH', 600436, '片仔癀', '中成药', 'SSE'),
 ('600438.SH', 600438, '通威股份', '电气设备', 'SSE'),
 ('600439.SH', 600439, '瑞贝卡', '服饰', 'SSE'),
 ('600444.SH', 600444, '国机通用', '专用机械', 'SSE'),
 ('600446.SH', 600446, '金证股份', '软件服务', 'SSE'),
 ('600448.SH', 600448, '华纺股份', '纺织', 'SSE'),
 ('600449.SH', 600449, '宁夏建材', '水泥', 'SSE'),
 ('600452.SH', 600452, '涪陵电力', '水力发电', 'SSE'),
 ('600455.SH', 600455, '博通股份', '文教休闲', 'SSE'),
 ('600456.SH', 600456, '宝钛股份', '小金属', 'SSE'),
 ('600458.SH', 600458, '时代新材', '塑料', 'SSE'),
 ('600459.SH', 600459, '贵研铂业', '小金属', 'SSE'),
 ('600460.SH', 600460, '士兰微', '半导体', 'SSE'),
 ('600461.SH', 600461, '洪城环境', '水务', 'SSE'),
 ('600462.SH', 600462, 'ST九有', '广告包装', 'SSE'),
 ('600463.SH', 600463, '空港股份', '园区开发', 'SSE'),
 ('600466.SH', 600466, '蓝光发展', '区域地产', 'SSE'),
 ('600467.SH', 600467, '好当家', '渔业', 'SSE'),
 ('600468.SH', 600468, '百利电气', '电气设备', 'SSE'),
 ('600469.SH', 600469, '风神股份', '汽车配件', 'SSE'),
 ('600470.SH', 600470, '六国化工', '农药化肥', 'SSE'),
 ('600475.SH', 600475, '华光环能', '环境保护', 'SSE'),
 ('600476.SH', 600476, '湘邮科技', '软件服务', 'SSE'),
 ('600477.SH', 600477, '杭萧钢构', '钢加工', 'SSE'),
 ('600478.SH', 600478, '科力远', '元器件', 'SSE'),
 ('600479.SH', 600479, '千金药业', '中成药', 'SSE'),
 ('600480.SH', 600480, '凌云股份', '汽车配件', 'SSE'),
 ('600481.SH', 600481, '双良节能', '机械基件', 'SSE'),
 ('600482.SH', 600482, '中国动力', '船舶', 'SSE'),
 ('600483.SH', 600483, '福能股份', '火力发电', 'SSE'),
 ('600486.SH', 600486, '扬农化工', '农药化肥', 'SSE'),
 ('600487.SH', 600487, '亨通光电', '通信设备', 'SSE'),
 ('600488.SH', 600488, '天药股份', '化学制药', 'SSE'),
 ('600489.SH', 600489, '中金黄金', '黄金', 'SSE'),
 ('600490.SH', 600490, '鹏欣资源', '铜', 'SSE'),
 ('600491.SH', 600491, '龙元建设', '建筑工程', 'SSE'),
 ('600493.SH', 600493, '凤竹纺织', '纺织', 'SSE'),
 ('600495.SH', 600495, '晋西车轴', '运输设备', 'SSE'),
 ('600496.SH', 600496, '精工钢构', '钢加工', 'SSE'),
 ('600497.SH', 600497, '驰宏锌锗', '铅锌', 'SSE'),
 ('600498.SH', 600498, '烽火通信', '通信设备', 'SSE'),
 ('600499.SH', 600499, '科达制造', '专用机械', 'SSE'),
 ('600500.SH', 600500, '中化国际', '塑料', 'SSE'),
 ('600501.SH', 600501, '航天晨光', '汽车配件', 'SSE'),
 ('600502.SH', 600502, '安徽建工', '建筑工程', 'SSE'),
 ('600503.SH', 600503, '华丽家族', '区域地产', 'SSE'),
 ('600505.SH', 600505, '西昌电力', '水力发电', 'SSE'),
 ('600506.SH', 600506, '香梨股份', '化工原料', 'SSE'),
 ('600507.SH', 600507, '方大特钢', '特种钢', 'SSE'),
 ('600508.SH', 600508, '上海能源', '煤炭开采', 'SSE'),
 ('600509.SH', 600509, '天富能源', '火力发电', 'SSE'),
 ('600510.SH', 600510, '黑牡丹', '全国地产', 'SSE'),
 ('600511.SH', 600511, '国药股份', '医药商业', 'SSE'),
 ('600512.SH', 600512, '腾达建设', '建筑工程', 'SSE'),
 ('600513.SH', 600513, '联环药业', '化学制药', 'SSE'),
 ('600515.SH', 600515, 'ST基础', '机场', 'SSE'),
 ('600516.SH', 600516, '方大炭素', '矿物制品', 'SSE'),
 ('600517.SH', 600517, '国网英大', '多元金融', 'SSE'),
 ('600518.SH', 600518, 'ST康美', '中成药', 'SSE'),
 ('600519.SH', 600519, '贵州茅台', '白酒', 'SSE'),
 ('600520.SH', 600520, '文一科技', '机械基件', 'SSE'),
 ('600521.SH', 600521, '华海药业', '化学制药', 'SSE'),
 ('600522.SH', 600522, '中天科技', '通信设备', 'SSE'),
 ('600523.SH', 600523, '贵航股份', '汽车配件', 'SSE'),
 ('600525.SH', 600525, '长园集团', '电气设备', 'SSE'),
 ('600526.SH', 600526, '菲达环保', '环境保护', 'SSE'),
 ('600527.SH', 600527, '江南高纤', '化纤', 'SSE'),
 ('600528.SH', 600528, '中铁工业', '运输设备', 'SSE'),
 ('600529.SH', 600529, '山东药玻', '医疗保健', 'SSE'),
 ('600530.SH', 600530, '交大昂立', '医疗保健', 'SSE'),
 ('600531.SH', 600531, '豫光金铅', '铅锌', 'SSE'),
 ('600532.SH', 600532, '*ST未来', '医疗保健', 'SSE'),
 ('600533.SH', 600533, '栖霞建设', '区域地产', 'SSE'),
 ('600535.SH', 600535, '天士力', '中成药', 'SSE'),
 ('600536.SH', 600536, '中国软件', '软件服务', 'SSE'),
 ('600537.SH', 600537, '亿晶光电', '电气设备', 'SSE'),
 ('600538.SH', 600538, '国发股份', '医药商业', 'SSE'),
 ('600539.SH', 600539, '狮头股份', '互联网', 'SSE'),
 ('600540.SH', 600540, '新赛股份', '种植业', 'SSE'),
 ('600543.SH', 600543, '莫高股份', '红黄酒', 'SSE'),
 ('600545.SH', 600545, '卓郎智能', '纺织机械', 'SSE'),
 ('600546.SH', 600546, '山煤国际', '煤炭开采', 'SSE'),
 ('600547.SH', 600547, '山东黄金', '黄金', 'SSE'),
 ('600548.SH', 600548, '深高速', '路桥', 'SSE'),
 ('600549.SH', 600549, '厦门钨业', '小金属', 'SSE'),
 ('600550.SH', 600550, '保变电气', '电气设备', 'SSE'),
 ('600551.SH', 600551, '时代出版', '出版业', 'SSE'),
 ('600552.SH', 600552, '凯盛科技', '玻璃', 'SSE'),
 ('600555.SH', 600555, '退海创', None, 'SSE'),

In [31]:
conn = sqlite3.connect('./ch/sse.db')

In [8]:
rows[0][0]

'600000.SH'

## 存储SSE

In [11]:
# Select SZSE List
conn = sqlite3.connect('ticker_symbol_ch.db')
cur = conn.cursor()
sql = """select * from SZSE"""
cur.execute(sql)
rows = cur.fetchall()
cur.close()
conn.close()
pro = ts.pro_api()

In [13]:
# 连接到sse数据库
conn = sqlite3.connect('./ch/sse.db')
# 获取rows的长度
len_ = len(rows)
for i in range(len_):
    # 获取单独的股票的历史记录
    df = pro.daily(ts_code = rows[i][0])
    # 创建表
    try:
        cursor = conn.cursor()
        cursor.execute('CREATE TABLE {}(ts_code, trade_date, open, high, low, close, change, pct_cha, vol)'.format(rows[i][0]))
        conn.commit()
        print("{} ceate successful!".format(rows[i][0]))
    except:
        print("Table name already exists")
    # 写入数据
    # 写入（如果没有就写入，否则建立资料表）
    try:
        df.to_sql('{}'.format(rows[i][0]), conn, if_exists='replace',index=False)
    except:
        print('df already exits')

Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists
Table name already exists

## 存储SZSE

In [ ]:
# 连接到sse数据库
conn = sqlite3.connect('./ch/szse.db')
# 获取rows的长度
len_ = len(rows)
for i in range(len_):
    # 获取单独的股票的历史记录
    df = pro.daily(ts_code = rows[i][0])
    # 创建表
    try:
        cursor = conn.cursor()
        cursor.execute('CREATE TABLE {}(ts_code, trade_date, open, high, low, close, change, pct_cha, vol)'.format(rows[i][0]))
        conn.commit()
        print("{} ceate successful!".format(rows[i][0]))
    except:
        print("Table name already exists")
    # 写入数据
    # 写入（如果没有就写入，否则建立资料表）
    try:
        df.to_sql('{}'.format(rows[i][0]), conn, if_exists='replace',index=False)
    except:
        print('df already exits')

In [33]:
df = pro.daily(ts_code='000001.SZ')
# df['exchange'] = 'SZSE'
df.tail()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
4995,000001.SZ,20010412,16.50,16.66,16.33,16.44,16.49,-0.05,-0.30,72915.15,120149.7936
4996,000001.SZ,20010411,16.70,16.70,16.38,16.49,16.40,0.09,0.55,39723.27,65524.9980
4997,000001.SZ,20010410,16.27,16.55,16.27,16.40,16.27,0.13,0.80,39710.22,65183.0994
4998,000001.SZ,20010409,16.31,16.40,16.15,16.27,16.31,-0.04,-0.25,43284.07,70248.5988
4999,000001.SZ,20010406,16.46,16.58,16.20,16.31,16.30,0.01,0.06,45613.12,74695.2758

解析法
```python
def get_df_from_db(sql):
    cursor = connection.cursor()
    cursor.execute(sql)
    data = cursor.fetchall()
    columnDes = cursor.description #获取连接对象的描述信息
    columnNames = [columnDes[i][0] for i in range(len(columnDes))]
    df = pd.DataFrame([list(i) for i in data],columns=columnNames)
    return df
```

# Pandas(Important)

In [4]:
from sqlalchemy import create_engine
engine= create_engine('sqlite:///ch/total_ch.db')

In [5]:
# Pandas
df = pd.read_sql('000001.SZ',engine)

In [6]:
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20220712,14.41,14.73,14.38,14.42,14.46,-0.04,-0.2766,742882.42,1.078432e+06
1,000001.SZ,20220711,14.50,14.57,14.36,14.46,14.54,-0.08,-0.5502,611691.94,8.836138e+05
2,000001.SZ,20220708,14.50,14.65,14.37,14.54,14.42,0.12,0.8322,639698.23,9.288503e+05
3,000001.SZ,20220707,14.54,14.65,14.38,14.42,14.53,-0.11,-0.7571,730160.98,1.057697e+06
4,000001.SZ,20220706,14.83,14.93,14.46,14.53,14.91,-0.38,-2.5486,1043335.23,1.520023e+06
...,...,...,...,...,...,...,...,...,...,...,...
4995,000001.SZ,20010412,16.50,16.66,16.33,16.44,16.49,-0.05,-0.3000,72915.15,1.201498e+05
4996,000001.SZ,20010411,16.70,16.70,16.38,16.49,16.40,0.09,0.5500,39723.27,6.552500e+04
4997,000001.SZ,20010410,16.27,16.55,16.27,16.40,16.27,0.13,0.8000,39710.22,6.518310e+04
4998,000001.SZ,20010409,16.31,16.40,16.15,16.27,16.31,-0.04,-0.2500,43284.07,7.024860e+04
4999,000001.SZ,20010406,16.46,16.58,16.20,16.31,16.30,0.01,0.0600,45613.12,7.469528e+04

In [38]:
try:
    cursor = conn.cursor()
    cursor.execute('CREATE TABLE {}(ts_code, trade_date, open, high, low, close, change, pct_cha, vol)'.format('000001'))
    conn.commit()
    print("Table ceate successful!")
except:
    print("Table name already exists")

Table name already exists

In [39]:
# 写入（如果没有就写入，否则建立资料表）
try:
    df.to_sql('{}'.format('000001.SZ'), conn, if_exists='replace',index=False)
except:
    print('df already exits')

In [4]:
conn = sqlite3.connect('./ch/sse.db')
cur = conn.cursor()
sql = """select * from '000001.SZ' """
cur.execute(sql)
rows = cur.fetchall()
# 获取链接对象的描述信息
columnDes = cur.description
columnNames = [columnDes[i][0] for i in range(len(columnDes))]
df = pd.DataFrame([list(i) for i in rows],columns=columnNames)
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20220712,14.41,14.73,14.38,14.42,14.46,-0.04,-0.2766,742882.42,1.078432e+06
1,000001.SZ,20220711,14.50,14.57,14.36,14.46,14.54,-0.08,-0.5502,611691.94,8.836138e+05
2,000001.SZ,20220708,14.50,14.65,14.37,14.54,14.42,0.12,0.8322,639698.23,9.288503e+05
3,000001.SZ,20220707,14.54,14.65,14.38,14.42,14.53,-0.11,-0.7571,730160.98,1.057697e+06
4,000001.SZ,20220706,14.83,14.93,14.46,14.53,14.91,-0.38,-2.5486,1043335.23,1.520023e+06
...,...,...,...,...,...,...,...,...,...,...,...
4995,000001.SZ,20010412,16.50,16.66,16.33,16.44,16.49,-0.05,-0.3000,72915.15,1.201498e+05
4996,000001.SZ,20010411,16.70,16.70,16.38,16.49,16.40,0.09,0.5500,39723.27,6.552500e+04
4997,000001.SZ,20010410,16.27,16.55,16.27,16.40,16.27,0.13,0.8000,39710.22,6.518310e+04
4998,000001.SZ,20010409,16.31,16.40,16.15,16.27,16.31,-0.04,-0.2500,43284.07,7.024860e+04
4999,000001.SZ,20010406,16.46,16.58,16.20,16.31,16.30,0.01,0.0600,45613.12,7.469528e+04

In [23]:
for item in rows:
    # print(item[0])
    # df = pro.daily(ts_code=item[0])
    # df.to_csv('./SSE/{}.csv'.format(item[0]))
    # create the table(only once)
    try:
        cursor = conn.cursor()
        cursor.execute('CREATE TABLE {}(ts_code, trade_date, open, high, low, close,change, pct_cha, vol, exchange)'.format(item[0]))
        conn.commit()
        print("Table ceate successful!")
    except:
        print("Table name already exists")

600000.SH
600004.SH
600006.SH
600007.SH
600008.SH
600009.SH
600010.SH
600011.SH
600012.SH
600015.SH
600016.SH
600017.SH
600018.SH
600019.SH
600020.SH
600021.SH
600022.SH
600023.SH
600025.SH
600026.SH
600027.SH
600028.SH
600029.SH
600030.SH
600031.SH
600032.SH
600033.SH
600035.SH
600036.SH
600037.SH
600038.SH
600039.SH
600048.SH
600050.SH
600051.SH
600052.SH
600053.SH
600054.SH
600055.SH
600056.SH
600057.SH
600058.SH
600059.SH
600060.SH
600061.SH
600062.SH
600063.SH
600064.SH
600066.SH
600067.SH
600070.SH
600071.SH
600072.SH
600073.SH
600075.SH
600076.SH
600077.SH
600078.SH
600079.SH
600080.SH
600081.SH
600082.SH
600083.SH
600084.SH
600085.SH
600088.SH
600089.SH
600094.SH
600095.SH
600096.SH
600097.SH
600098.SH
600099.SH
600100.SH
600101.SH
600103.SH
600104.SH
600105.SH
600106.SH
600107.SH
600108.SH
600109.SH
600110.SH
600111.SH
600112.SH
600113.SH
600114.SH
600115.SH
600116.SH
600117.SH
600118.SH
600119.SH
600120.SH
600121.SH
600122.SH
600123.SH
600125.SH
600126.SH
600127.SH
600128.SH
600129.SH
600130.SH
600131.SH
600132.SH
600133.SH
600135.SH
600136.SH
600137.SH
600138.SH
600139.SH
600141.SH
600143.SH
600148.SH
600149.SH
600150.SH
600151.SH
600152.SH
600153.SH
600155.SH
600156.SH
600157.SH
600158.SH
600159.SH
600160.SH
600161.SH
600162.SH
600163.SH
600165.SH
600166.SH
600167.SH
600168.SH
600169.SH
600170.SH
600171.SH
600172.SH
600173.SH
600176.SH
600177.SH
600178.SH
600179.SH
600180.SH
600182.SH
600183.SH
600184.SH
600185.SH
600186.SH
600187.SH
600188.SH
600189.SH
600190.SH
600191.SH
600192.SH
600193.SH
600195.SH
600196.SH
600197.SH
600198.SH
600199.SH
600200.SH
600201.SH
600202.SH
600203.SH
600206.SH
600207.SH
600208.SH
600210.SH
600211.SH
600212.SH
600213.SH
600215.SH
600216.SH
600217.SH
600218.SH
600219.SH
600220.SH
600221.SH
600222.SH
600223.SH
600225.SH
600226.SH
600227.SH
600228.SH
600229.SH
600230.SH
600231.SH
600232.SH
600233.SH
600234.SH
600235.SH
600236.SH
600237.SH
600238.SH
600239.SH
600241.SH
600242.SH
600243.SH
600246.SH
600248.SH
600249.SH
600250.SH
600251.SH
600252.SH
600255.SH
600256.SH
600257.SH
600258.SH
600259.SH
600260.SH
600261.SH
600262.SH
600265.SH
600266.SH
600267.SH
600268.SH
600269.SH
600271.SH
600272.SH
600273.SH
600276.SH
600277.SH
600278.SH
600279.SH
600280.SH
600281.SH
600282.SH
600283.SH
600284.SH
600285.SH
600287.SH
600288.SH
600289.SH
600290.SH
600292.SH
600293.SH
600295.SH
600297.SH
600298.SH
600299.SH
600300.SH
600301.SH
600302.SH
600303.SH
600305.SH
600306.SH
600307.SH
600308.SH
600309.SH
600310.SH
600311.SH
600312.SH
600313.SH
600315.SH
600316.SH
600318.SH
600319.SH
600320.SH
600321.SH
600322.SH
600323.SH
600325.SH
600326.SH
600327.SH
600328.SH
600329.SH
600330.SH
600331.SH
600332.SH
600333.SH
600335.SH
600336.SH
600337.SH
600338.SH
600339.SH
600340.SH
600343.SH
600345.SH
600346.SH
600348.SH
600350.SH
600351.SH
600352.SH
600353.SH
600354.SH
600355.SH
600356.SH
600358.SH
600359.SH
600360.SH
600361.SH
600362.SH
600363.SH
600365.SH
600366.SH
600367.SH
600368.SH
600369.SH
600370.SH
600371.SH
600372.SH
600373.SH
600375.SH
600376.SH
600377.SH
600378.SH
600379.SH
600380.SH
600381.SH
600382.SH
600383.SH
600386.SH
600387.SH
600388.SH
600389.SH
600390.SH
600391.SH
600392.SH
600393.SH
600395.SH
600396.SH
600397.SH
600398.SH
600399.SH
600400.SH
600403.SH
600405.SH
600406.SH
600408.SH
600409.SH
600410.SH
600415.SH
600416.SH
600418.SH
600419.SH
600420.SH
600421.SH
600422.SH
600423.SH
600425.SH
600426.SH
600428.SH
600429.SH
600433.SH
600435.SH
600436.SH
600438.SH
600439.SH
600444.SH
600446.SH
600448.SH
600449.SH
600452.SH
600455.SH
600456.SH
600458.SH
600459.SH
600460.SH
600461.SH
600462.SH
600463.SH
600466.SH
600467.SH
600468.SH
600469.SH
600470.SH
600475.SH
600476.SH
600477.SH
600478.SH
600479.SH
600480.SH
600481.SH
600482.SH
600483.SH
600486.SH
600487.SH
600488.SH
600489.SH
600490.SH
600491.SH
600493.SH
600495.SH
600496.SH
600497.SH
600498.SH
600499.SH
600500.SH
600501.SH
600502.SH
600503.SH
600505.SH
600506.SH
600507.SH
600508.SH
600509.SH
600510.SH
600511.SH
600512.SH
600513.SH
600515.SH
600516.SH
600517.SH
600518.SH
600519.SH
600520.SH
600521.SH
600522.SH
600523.SH
600525.SH
600526.SH
600527.SH
600528.SH
600529.SH
600530.SH
600531.SH
600532.SH
600533.SH
600535.SH
600536.SH
600537.SH
600538.SH
600539.SH
600540.SH
600543.SH
600545.SH
600546.SH
600547.SH
600548.SH
600549.SH
600550.SH
600551.SH
600552.SH
600555.SH
600556.SH
600557.SH
600558.SH
600559.SH
600560.SH
600561.SH
600562.SH
600563.SH
600565.SH
600566.SH
600567.SH
600568.SH
600569.SH
600570.SH
600571.SH
600572.SH
600573.SH
600575.SH
600576.SH
600577.SH
600578.SH
600579.SH
600580.SH
600581.SH
600582.SH
600583.SH
600584.SH
600585.SH
600586.SH
600587.SH
600588.SH
600589.SH
600590.SH
600592.SH
600593.SH
600594.SH
600595.SH
600596.SH
600597.SH
600598.SH
600599.SH
600600.SH
600601.SH
600602.SH
600603.SH
600604.SH
600605.SH
600606.SH
600608.SH
600609.SH
600610.SH
600611.SH
600612.SH
600613.SH
600615.SH
600616.SH
600617.SH
600618.SH
600619.SH
600620.SH
600621.SH
600622.SH
600623.SH
600624.SH
600626.SH
600628.SH
600629.SH
600630.SH
600633.SH
600635.SH
600636.SH
600637.SH
600638.SH
600639.SH
600640.SH
600641.SH
600642.SH
600643.SH
600644.SH
600645.SH
600647.SH
600648.SH
600649.SH
600650.SH
600651.SH
600653.SH
600654.SH
600655.SH
600657.SH
600658.SH
600660.SH
600661.SH
600662.SH
600663.SH
600664.SH
600665.SH
600666.SH
600667.SH
600668.SH
600671.SH
600673.SH
600674.SH
600675.SH
600676.SH
600678.SH
600679.SH
600681.SH
600682.SH
600683.SH
600684.SH
600685.SH
600686.SH
600688.SH
600689.SH
600690.SH
600691.SH
600692.SH
600693.SH
600694.SH
600696.SH
600697.SH
600698.SH
600699.SH
600702.SH
600703.SH
600704.SH
600705.SH
600706.SH
600707.SH
600708.SH
600710.SH
600711.SH
600712.SH
600713.SH
600714.SH
600715.SH
600716.SH
600717.SH
600718.SH
600719.SH
600720.SH
600721.SH
600722.SH
600724.SH
600725.SH
600726.SH
600727.SH
600728.SH
600729.SH
600730.SH
600731.SH
600732.SH
600733.SH
600734.SH
600735.SH
600736.SH
600737.SH
600738.SH
600739.SH
600740.SH
600741.SH
600742.SH
600743.SH
600744.SH
600745.SH
600746.SH
600748.SH
600749.SH
600750.SH
600751.SH
600753.SH
600754.SH
600755.SH
600756.SH
600757.SH
600758.SH
600759.SH
600760.SH
600761.SH
600763.SH
600764.SH
600765.SH
600766.SH
600767.SH
600768.SH
600769.SH
600770.SH
600771.SH
600773.SH
600774.SH
600775.SH
600776.SH
600777.SH
600778.SH
600779.SH
600780.SH
600781.SH
600782.SH
600783.SH
600784.SH
600785.SH
600787.SH
600789.SH
600790.SH
600791.SH
600792.SH
600793.SH
600794.SH
600795.SH
600796.SH
600797.SH
600798.SH
600800.SH
600801.SH
600802.SH
600803.SH
600804.SH
600805.SH
600807.SH
600808.SH
600809.SH
600810.SH
600811.SH
600812.SH
600814.SH
600815.SH
600816.SH
600817.SH
600818.SH
600819.SH
600820.SH
600821.SH
600822.SH
600823.SH
600824.SH
600825.SH
600826.SH
600827.SH
600828.SH
600829.SH
600830.SH
600831.SH
600833.SH
600834.SH
600835.SH
600836.SH
600837.SH
600838.SH
600839.SH
600841.SH
600843.SH
600844.SH
600845.SH
600846.SH
600847.SH
600848.SH
600850.SH
600851.SH
600853.SH
600854.SH
600855.SH
600857.SH
600858.SH
600859.SH
600860.SH
600861.SH
600862.SH
600863.SH
600864.SH
600865.SH
600866.SH
600867.SH
600868.SH
600869.SH
600871.SH
600872.SH
600873.SH
600874.SH
600875.SH
600876.SH
600877.SH
600879.SH
600880.SH
600881.SH
600882.SH
600883.SH
600884.SH
600885.SH
600886.SH
600887.SH
600888.SH
600889.SH
600892.SH
600893.SH
600894.SH
600895.SH
600896.SH
600897.SH
600898.SH
600900.SH
600901.SH
600903.SH
600905.SH
600906.SH
600908.SH
600909.SH
600916.SH
600917.SH
600918.SH
600919.SH
600926.SH
600927.SH
600928.SH
600929.SH
600933.SH
600935.SH
600936.SH
600938.SH
600939.SH
600941.SH
600955.SH
600956.SH
600958.SH
600959.SH
600960.SH
600961.SH
600962.SH
600963.SH
600965.SH
600966.SH
600967.SH
600968.SH
600969.SH
600970.SH
600971.SH
600973.SH
600975.SH
600976.SH
600977.SH
600979.SH
600980.SH
600981.SH
600982.SH
600983.SH
600984.SH
600985.SH
600986.SH
600987.SH
600988.SH
600989.SH
600990.SH
600992.SH
600993.SH
600995.SH
600996.SH
600997.SH
600998.SH
600999.SH
601000.SH
601001.SH
601002.SH
601003.SH
601005.SH
601006.SH
601007.SH
601008.SH
601009.SH
601010.SH
601011.SH
601012.SH
601015.SH
601016.SH
601018.SH
601019.SH
601020.SH
601021.SH
601028.SH
601038.SH
601058.SH
601066.SH
601068.SH
601069.SH
601077.SH
601086.SH
601088.SH
601089.SH
601098.SH
601099.SH
601100.SH
601101.SH
601106.SH
601107.SH
601108.SH
601111.SH
601113.SH
601116.SH
601117.SH
601118.SH
601126.SH
601127.SH
601128.SH
601137.SH
601138.SH
601139.SH
601155.SH
601156.SH
601158.SH
601162.SH
601163.SH
601166.SH
601168.SH
601169.SH
601177.SH
601179.SH
601186.SH
601187.SH
601188.SH
601198.SH
601199.SH
601200.SH
601208.SH
601211.SH
601212.SH
601216.SH
601218.SH
601222.SH
601225.SH
601226.SH
601228.SH
601229.SH
601231.SH
601233.SH
601236.SH
601238.SH
601258.SH
601279.SH
601288.SH
601298.SH
601311.SH
601318.SH
601319.SH
601326.SH
601328.SH
601330.SH
601333.SH
601336.SH
601339.SH
601360.SH
601366.SH
601368.SH
601369.SH
601375.SH
601377.SH
601388.SH
601390.SH
601398.SH
601399.SH
601456.SH
601500.SH
601512.SH
601515.SH
601518.SH
601519.SH
601528.SH
601555.SH
601566.SH
601567.SH
601568.SH
601577.SH
601579.SH
601588.SH
601595.SH
601598.SH
601599.SH
601600.SH
601601.SH
601606.SH
601607.SH
601608.SH
601609.SH
601611.SH
601615.SH
601616.SH
601618.SH
601619.SH
601628.SH
601633.SH
601636.SH
601658.SH
601665.SH
601666.SH
601668.SH
601669.SH
601677.SH
601678.SH
601686.SH
601688.SH
601689.SH
601696.SH
601698.SH
601699.SH
601700.SH
601702.SH
601717.SH
601718.SH
601727.SH
601728.SH
601766.SH
601777.SH
601778.SH
601788.SH
601789.SH
601798.SH
601799.SH
601800.SH
601801.SH
601808.SH
601811.SH
601816.SH
601818.SH
601825.SH
601827.SH
601828.SH
601838.SH
601857.SH
601858.SH
601860.SH
601865.SH
601866.SH
601868.SH
601869.SH
601872.SH
601877.SH
601878.SH
601880.SH
601881.SH
601882.SH
601886.SH
601888.SH
601890.SH
601898.SH
601899.SH
601900.SH
601901.SH
601908.SH
601916.SH
601918.SH
601919.SH
601921.SH
601928.SH
601929.SH
601933.SH
601939.SH
601949.SH
601952.SH
601956.SH
601958.SH
601963.SH
601965.SH
601966.SH
601968.SH
601969.SH
601975.SH
601985.SH
601988.SH
601989.SH
601990.SH
601991.SH
601992.SH
601995.SH
601996.SH
601997.SH
601998.SH
601999.SH
603000.SH
603001.SH
603002.SH
603003.SH
603005.SH
603006.SH
603007.SH
603008.SH
603009.SH
603010.SH
603011.SH
603012.SH
603013.SH
603015.SH
603016.SH
603017.SH
603018.SH
603019.SH
603020.SH
603021.SH
603022.SH
603023.SH
603025.SH
603026.SH
603027.SH
603028.SH
603029.SH
603030.SH
603031.SH
603032.SH
603033.SH
603035.SH
603036.SH
603037.SH
603038.SH
603039.SH
603040.SH
603041.SH
603042.SH
603043.SH
603045.SH
603048.SH
603050.SH
603051.SH
603053.SH
603055.SH
603056.SH
603058.SH
603059.SH
603060.SH
603063.SH
603066.SH
603067.SH
603068.SH
603069.SH
603070.SH
603071.SH
603076.SH
603077.SH
603078.SH
603079.SH
603080.SH
603081.SH
603083.SH
603085.SH
603086.SH
603087.SH
603088.SH
603089.SH
603090.SH
603093.SH
603095.SH
603096.SH
603097.SH
603098.SH
603099.SH
603100.SH
603101.SH
603102.SH
603103.SH
603105.SH
603106.SH
603108.SH
603109.SH
603110.SH
603111.SH
603112.SH
603113.SH
603115.SH
603116.SH
603117.SH
603118.SH
603121.SH
603122.SH
603123.SH
603126.SH
603127.SH
603128.SH
603129.SH
603131.SH
603132.SH
603133.SH
603136.SH
603138.SH
603139.SH
603150.SH
603155.SH
603156.SH
603158.SH
603159.SH
603160.SH
603161.SH
603165.SH
603166.SH
603167.SH
603168.SH
603169.SH
603171.SH
603176.SH
603177.SH
603178.SH
603179.SH
603180.SH
603181.SH
603183.SH
603185.SH
603186.SH
603187.SH
603188.SH
603189.SH
603191.SH
603192.SH
603195.SH
603196.SH
603197.SH
603198.SH
603199.SH
603200.SH
603203.SH
603206.SH
603208.SH
603209.SH
603212.SH
603213.SH
603214.SH
603215.SH
603216.SH
603217.SH
603218.SH
603219.SH
603220.SH
603221.SH
603222.SH
603223.SH
603225.SH
603226.SH
603227.SH
603228.SH
603229.SH
603230.SH
603232.SH
603233.SH
603235.SH
603236.SH
603238.SH
603239.SH
603256.SH
603258.SH
603259.SH
603260.SH
603261.SH
603266.SH
603267.SH
603268.SH
603269.SH
603272.SH
603277.SH
603278.SH
603279.SH
603283.SH
603286.SH
603288.SH
603289.SH
603290.SH
603297.SH
603298.SH
603299.SH
603300.SH
603301.SH
603303.SH
603305.SH
603306.SH
603308.SH
603309.SH
603311.SH
603313.SH
603315.SH
603316.SH
603317.SH
603318.SH
603319.SH
603320.SH
603321.SH
603322.SH
603323.SH
603324.SH
603326.SH
603327.SH
603328.SH
603329.SH
603330.SH
603331.SH
603332.SH
603333.SH
603335.SH
603336.SH
603337.SH
603338.SH
603339.SH
603345.SH
603348.SH
603351.SH
603353.SH
603355.SH
603356.SH
603357.SH
603358.SH
603359.SH
603360.SH
603363.SH
603365.SH
603366.SH
603367.SH
603368.SH
603369.SH
603377.SH
603378.SH
603379.SH
603380.SH
603383.SH
603385.SH
603386.SH
603387.SH
603388.SH
603389.SH
603390.SH
603392.SH
603393.SH
603396.SH
603398.SH
603399.SH
603408.SH
603416.SH
603421.SH
603429.SH
603439.SH
603444.SH
603456.SH
603458.SH
603466.SH
603477.SH
603486.SH
603488.SH
603489.SH
603496.SH
603499.SH
603500.SH
603501.SH
603505.SH
603506.SH
603507.SH
603508.SH
603511.SH
603515.SH
603516.SH
603517.SH
603518.SH
603519.SH
603520.SH
603527.SH
603528.SH
603529.SH
603530.SH
603533.SH
603535.SH
603536.SH
603538.SH
603551.SH
603555.SH
603556.SH
603557.SH
603558.SH
603559.SH
603565.SH
603566.SH
603567.SH
603568.SH
603569.SH
603577.SH
603578.SH
603579.SH
603580.SH
603583.SH
603585.SH
603586.SH
603587.SH
603588.SH
603589.SH
603590.SH
603595.SH
603596.SH
603598.SH
603599.SH
603600.SH
603601.SH
603602.SH
603603.SH
603605.SH
603606.SH
603607.SH
603608.SH
603609.SH
603610.SH
603611.SH
603612.SH
603613.SH
603615.SH
603616.SH
603617.SH
603618.SH
603619.SH
603626.SH
603628.SH
603629.SH
603630.SH
603633.SH
603636.SH
603637.SH
603638.SH
603639.SH
603648.SH
603650.SH
603655.SH
603656.SH
603657.SH
603658.SH
603659.SH
603660.SH
603661.SH
603662.SH
603663.SH
603665.SH
603666.SH
603667.SH
603668.SH
603669.SH
603676.SH
603677.SH
603678.SH
603679.SH
603680.SH
603681.SH
603682.SH
603683.SH
603685.SH
603686.SH
603687.SH
603688.SH
603689.SH
603690.SH
603693.SH
603696.SH
603697.SH
603698.SH
603699.SH
603700.SH
603701.SH
603703.SH
603706.SH
603707.SH
603708.SH
603709.SH
603711.SH
603712.SH
603713.SH
603716.SH
603717.SH
603718.SH
603719.SH
603721.SH
603722.SH
603725.SH
603726.SH
603727.SH
603728.SH
603729.SH
603730.SH
603733.SH
603737.SH
603738.SH
603739.SH
603755.SH
603757.SH
603758.SH
603759.SH
603766.SH
603767.SH
603768.SH
603773.SH
603776.SH
603777.SH
603778.SH
603779.SH
603786.SH
603787.SH
603788.SH
603789.SH
603790.SH
603797.SH
603798.SH
603799.SH
603800.SH
603801.SH
603803.SH
603806.SH
603808.SH
603809.SH
603810.SH
603811.SH
603813.SH
603815.SH
603816.SH
603817.SH
603818.SH
603819.SH
603822.SH
603823.SH
603825.SH
603826.SH
603828.SH
603829.SH
603833.SH
603836.SH
603838.SH
603839.SH
603843.SH
603848.SH
603855.SH
603856.SH
603858.SH
603859.SH
603860.SH
603861.SH
603863.SH
603866.SH
603867.SH
603868.SH
603869.SH
603871.SH
603876.SH
603877.SH
603878.SH
603879.SH
603880.SH
603881.SH
603882.SH
603883.SH
603885.SH
603886.SH
603887.SH
603888.SH
603889.SH
603890.SH
603893.SH
603895.SH
603896.SH
603897.SH
603898.SH
603899.SH
603900.SH
603901.SH
603903.SH
603906.SH
603908.SH
603909.SH
603912.SH
603915.SH
603916.SH
603917.SH
603918.SH
603919.SH
603920.SH
603922.SH
603926.SH
603927.SH
603928.SH
603929.SH
603931.SH
603933.SH
603936.SH
603937.SH
603938.SH
603939.SH
603948.SH
603949.SH
603950.SH
603955.SH
603956.SH
603958.SH
603959.SH
603960.SH
603963.SH
603966.SH
603967.SH
603968.SH
603969.SH
603970.SH
603976.SH
603977.SH
603978.SH
603979.SH
603980.SH
603982.SH
603983.SH
603985.SH
603986.SH
603987.SH
603988.SH
603989.SH
603990.SH
603991.SH
603992.SH
603993.SH
603995.SH
603997.SH
603998.SH
603999.SH
605001.SH
605003.SH
605005.SH
605006.SH
605007.SH
605008.SH
605009.SH
605011.SH
605016.SH
605018.SH
605020.SH
605028.SH
605033.SH
605050.SH
605055.SH
605056.SH
605058.SH
605060.SH
605066.SH
605068.SH
605069.SH
605077.SH
605080.SH
605081.SH
605086.SH
605088.SH
605089.SH
605090.SH
605098.SH
605099.SH
605100.SH
605108.SH
605111.SH
605116.SH
605117.SH
605118.SH
605122.SH
605123.SH
605128.SH
605133.SH
605136.SH
605138.SH
605151.SH
605155.SH
605158.SH
605162.SH
605166.SH
605167.SH
605168.SH
605169.SH
605177.SH
605178.SH
605179.SH
605180.SH
605183.SH
605186.SH
605188.SH
605189.SH
605196.SH
605198.SH
605199.SH
605208.SH
605218.SH
605222.SH
605228.SH
605255.SH
605258.SH
605259.SH
605266.SH
605268.SH
605277.SH
605286.SH
605287.SH
605288.SH
605289.SH
605296.SH
605298.SH
605299.SH
605300.SH
605303.SH
605305.SH
605318.SH
605319.SH
605333.SH
605336.SH
605337.SH
605338.SH
605339.SH
605358.SH
605365.SH
605366.SH
605368.SH
605369.SH
605376.SH
605377.SH
605378.SH
605388.SH
605389.SH
605398.SH
605399.SH
605488.SH
605499.SH
605500.SH
605507.SH
605555.SH
605566.SH
605567.SH
605577.SH
605580.SH
605588.SH
605589.SH
605598.SH
605599.SH
688001.SH
688002.SH
688003.SH
688004.SH
688005.SH
688006.SH
688007.SH
688008.SH
688009.SH
688010.SH
688011.SH
688012.SH
688013.SH
688015.SH
688016.SH
688017.SH
688018.SH
688019.SH
688020.SH
688021.SH
688022.SH
688023.SH
688025.SH
688026.SH
688027.SH
688028.SH
688029.SH
688030.SH
688032.SH
688033.SH
688036.SH
688037.SH
688038.SH
688039.SH
688045.SH
688046.SH
688047.SH
688048.SH
688049.SH
688050.SH
688051.SH
688052.SH
688053.SH
688055.SH
688056.SH
688057.SH
688058.SH
688059.SH
688060.SH
688062.SH
688063.SH
688065.SH
688066.SH
688067.SH
688068.SH
688069.SH
688070.SH
688071.SH
688072.SH
688075.SH
688076.SH
688077.SH
688078.SH
688079.SH
688080.SH
688081.SH
688082.SH
688083.SH
688085.SH
688086.SH
688087.SH
688088.SH
688089.SH
688090.SH
688091.SH
688092.SH
688093.SH
688095.SH
688096.SH
688097.SH
688098.SH
688099.SH
688100.SH
688101.SH
688102.SH
688103.SH
688105.SH
688106.SH
688107.SH
688108.SH
688109.SH
688110.SH
688111.SH
688112.SH
688113.SH
688115.SH
688116.SH
688117.SH
688118.SH
688119.SH
688120.SH
688121.SH
688122.SH
688123.SH
688125.SH
688126.SH
688127.SH
688128.SH
688129.SH
688131.SH
688133.SH
688135.SH
688136.SH
688138.SH
688139.SH
688148.SH
688150.SH
688151.SH
688153.SH
688155.SH
688156.SH
688157.SH
688158.SH
688159.SH
688160.SH
688161.SH
688162.SH
688163.SH
688165.SH
688166.SH
688167.SH
688168.SH
688169.SH
688170.SH
688171.SH
688173.SH
688175.SH
688176.SH
688177.SH
688178.SH
688179.SH
688180.SH
688181.SH
688182.SH
688183.SH
688185.SH
688186.SH
688187.SH
688188.SH
688189.SH
688190.SH
688191.SH
688192.SH
688193.SH
688195.SH
688196.SH
688197.SH
688198.SH
688199.SH
688200.SH
688201.SH
688202.SH
688206.SH
688207.SH
688208.SH
688209.SH
688210.SH
688211.SH
688212.SH
688213.SH
688215.SH
688216.SH
688217.SH
688218.SH
688219.SH
688220.SH
688221.SH
688222.SH
688223.SH
688225.SH
688226.SH
688227.SH
688228.SH
688229.SH
688230.SH
688232.SH
688233.SH
688234.SH
688235.SH
688236.SH
688237.SH
688238.SH
688239.SH
688246.SH
688248.SH
688251.SH
688255.SH
688256.SH
688257.SH
688258.SH
688259.SH
688260.SH
688261.SH
688262.SH
688265.SH
688266.SH
688267.SH
688268.SH
688269.SH
688270.SH
688272.SH
688276.SH
688277.SH
688278.SH
688279.SH
688280.SH
688281.SH
688282.SH
688283.SH
688285.SH
688286.SH
688287.SH
688288.SH
688289.SH
688290.SH
688295.SH
688296.SH
688297.SH
688298.SH
688299.SH
688300.SH
688301.SH
688302.SH
688303.SH
688305.SH
688306.SH
688308.SH
688309.SH
688310.SH
688311.SH
688312.SH
688313.SH
688314.SH
688315.SH
688316.SH
688317.SH
688318.SH
688319.SH
688320.SH
688321.SH
688322.SH
688323.SH
688325.SH
688326.SH
688327.SH
688328.SH
688329.SH
688330.SH
688331.SH
688333.SH
688335.SH
688336.SH
688337.SH
688338.SH
688339.SH
688345.SH
688348.SH
688349.SH
688350.SH
688353.SH
688355.SH
688356.SH
688357.SH
688358.SH
688359.SH
688360.SH
688363.SH
688365.SH
688366.SH
688367.SH
688368.SH
688369.SH
688377.SH
688378.SH
688379.SH
688383.SH
688385.SH
688386.SH
688388.SH
688389.SH
688390.SH
688393.SH
688395.SH
688396.SH
688398.SH
688399.SH
688400.SH
688408.SH
688418.SH
688425.SH
688456.SH
688466.SH
688468.SH
688488.SH
688499.SH
688500.SH
688501.SH
688505.SH
688508.SH
688509.SH
688510.SH
688511.SH
688513.SH
688516.SH
688517.SH
688518.SH
688519.SH
688520.SH
688521.SH
688526.SH
688528.SH
688529.SH
688533.SH
688536.SH
688538.SH
688550.SH
688551.SH
688553.SH
688555.SH
688556.SH
688557.SH
688558.SH
688559.SH
688560.SH
688561.SH
688565.SH
688566.SH
688567.SH
688568.SH
688569.SH
688571.SH
688575.SH
688577.SH
688578.SH

In [19]:
df = pro.daily(ts_code='000001.SZ')
df.tail()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
4995,000001.SZ,20010412,16.50,16.66,16.33,16.44,16.49,-0.05,-0.30,72915.15,120149.7936
4996,000001.SZ,20010411,16.70,16.70,16.38,16.49,16.40,0.09,0.55,39723.27,65524.9980
4997,000001.SZ,20010410,16.27,16.55,16.27,16.40,16.27,0.13,0.80,39710.22,65183.0994
4998,000001.SZ,20010409,16.31,16.40,16.15,16.27,16.31,-0.04,-0.25,43284.07,70248.5988
4999,000001.SZ,20010406,16.46,16.58,16.20,16.31,16.30,0.01,0.06,45613.12,74695.2758

In [21]:
df.to_csv('./SSE/{}.csv'.format('000001.SZ'))